config:
  # 根据实际情况修改以下参数
  TRAIN_IMAGE_PATH: 'path/to/training/images/folder/'
  TRAIN_ANNOTATION_PATH: 'path/to/training/annotation/folder/'
  VAL_IMAGE_PATH : 'path/to/validation/images/folder/'
  VAL_ANNOTATION_PATH : 'path/to/validation/annotation/folder/'
  PRETRAINED_MODEL_PATH : 'path/to/pre-trained/model/file'
  CHECKPOINT_PATH : 'path/to/checkpoints/folder/'

  # 模型参数
  BATCH_SIZE : 32
  IMAGE_SIZE : (224, 244)  # 图像输入尺寸
  ANCHOR_SCALES : [8, 16, 32]  # anchor的尺寸
  ANCHOR_RATIOS : [0.5, 1, 2]  # anchor的宽高比
  ANCHOR_STRIDE : 16  # anchor之间的距离
  POSITIVE_IOU_THRESHOLD : 0.7  # 正样本IOU的阈值
  NEGATIVE_IOU_THRESHOLD : 0.3  # 负样本IOU的阈值
  BALANCE_FACTOR : 0.33  # 正负样本抽样的权重因子
  MAX_GT_BOXES : 100  # 最大GT box的数量
  USE_SIDE_REFINE : True  # 是否使用CTPN+RNN中的RNN模块
  RNN_HIDDEN_SIZE : 256  # RNN模块的隐藏层大小
  RNN_NUM_LAYERS : 2  # RNN模块的层数
  RNN_DROPOUT_RATIO : 0.5  # RNN模块的dropout概率
  LEARNING_RATE : 0.01  # 模型学习率
  WEIGHT_DECAY : 0.0005  # 模型权重衰减率
  GRADIENT_CLIP : 5.0  # 梯度裁剪的最大值
  TRAIN_EPOCHS : 100  # 训练轮数
  VAL_STEP : 500  # 验证间隔步数
  SAVE_STEP : 500  # 保存间隔步数
  NUM_WORKERS : 8  # 数据加载的worker数量
